name: Notex
options:
  bundleIdPrefix: com.sercansolmaz
  deploymentTarget:
    macOS: "14.0"
  developmentLanguage: tr
settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: minimal
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_NSHumanReadableCopyright: "© 2026 Sercan Solmaz"
    INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
targets:
  Notex:
    type: application
    platform: macOS
    sources:
      - path: Notex
    dependencies:
      - sdk: libsqlite3.tbd
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sercansolmaz.notex
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
    scheme:
      name: Notex
      build:
        targets:
          Notex: all
